### ISSUE TITLE
Display something in amazon page to stop us buying from it

### ISSUE THREAD

**Issue by PhieF** [adriantombu/universal-amazon-killer#32]
Hi

Because we are a lot to have bad habits
it would be nice if, when visiting a book page, the extension modifies the page to add a button to buy from Place des libraires or displays a big "stop" dismissable in the middle of the page ! 

Thanks for your work ! Great extension ! :)

**Comment by adriantombu** [comment]
Nice idea, I will work on it as soon as I have some free time !

Maybe by deactivating the Amazon "Buy" button and displaying a message "Are you sure you wan't to buy this book on Amazon instead of Place des libraires" when we click on it ?

**Comment by adriantombu** [comment]
Hello @PhieF, I finaly had time to hack something together !
Now the primary "add to cart" button is gray and you get a prompt window to confirm that you really wanna buy in Amazon instead of a proposed alternative 😊
